version: '3'
services:
  db:
    image: postgres:16.0
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:z
    networks:
      - gwbackend-net
  rabbitmq:
    image: rabbitmq:3.9-management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
    networks:
      - gwbackend-net

volumes:
  rabbitmq_data:
  rabbitmq_log:

networks:
  gwbackend-net:
    driver: bridge