server:
  port: 5001
  servlet:
    context-path: /api

spring:
  application:
    name: GW Webservice
  profiles:
    include: db, local
  jackson:
    date-format: dd/MM/yyyy HH:mm
    time-zone: GMT+7
  mail:
    host: smtp.gmail.com
    port: 587
    username: phongpnggcc200002@fpt.edu.vn
    password: obik pipt gagr fkyk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    contribution: contribution_queue_1640
    user: user_queue_1640
  exchange:
    name: exchange_1640
  routing:
    contribution: contribution_rounting_key_1640
    user: user_routing_key_1640


management:
  server:
    port: 5002
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always

logging:
  level:
    root: INFO
    com.example.backend1640: INFO
  file:
    name: logs/gw-backend.log
