logging:
  level:
    com.example.backend1640: TRACE

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      schema: postgres
  jpa:
    show-sql: false
  flyway:
    create-schemas: true
    schemas: flyway
    enabled: true
    locations: classpath:db/migration,classpath:db/local

