logging:
  level:
    com.example.backend1640: TRACE

spring:
  datasource:
    url: jdbc:postgresql://ec2-54-251-135-241.ap-southeast-1.compute.amazonaws.com:5432/postgres
    username: postgres
    password: postgres
    hikari:
      schema: gwbackend
  jpa:
    show-sql: false
    properties:
      hibernate:
        ddl-auto: update
        default_schema: gwbackend
  flyway:
    create-schemas: true
    schemas: flyway
    enabled: true
    locations: classpath:db/migration,classpath:db/staging
  jackson:
    date-format: dd/MM/yyyy HH:mm
    time-zone: GMT+7
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 200MB
  rabbitmq:
    host: ec2-54-251-135-241.ap-southeast-1.compute.amazonaws.com
    port: 5672
    username: guest
    password: guest